cheng:
  btlusermrg:
    datasource:
      driver-class-name: "com.mysql.jdbc.Driver"
      url: "jdbc:mysql://127.0.0.1:3306/beetlsql?useUnicode=yes&characterEncoding=UTF-8"
      username: "root"
      password: "root"

