server:
  port: 80
  
spring:
  session:
    store-type: none
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/beetlsql?useUnicode=yes&characterEncoding=UTF-8
    username: root
    data-password: "000000"

beetlsql:
  enabled: false
  sqlPath: /sql
  nameConversion: org.beetl.sql.core.UnderlinedNameConversion
  dev: true
  daoSuffix: Dao
  basePackage: com.cheng.beetl.spring.dao
  dbStyle: org.beetl.sql.core.db.MySqlStyle
  pojoPackage: com.cheng.beetl.spring.pojo

beetl:
  enabled: true
  
FN:
  upper: com.cheng.beetl.function.Upper
  lower: com.cheng.beetlsql.function.Lower

cheng:
#安全配置
  security:
  #启用默认公开资源，js, html, png, ico等等, 默认开启
    enabled-default-permit-all: true
    #表单认证配置
    form:
    #登录页面
      login-page: /sign-in
      #登录url
      login-processing-url: /security-auth
      #登录成功跳转
      index-page: /index
      #登出url
      logout-proccess-url: /logout
    session:
      max-sessions-prevents-login: false
      maximum-sessions: 1
      expired-url: /session/expired
      invalid-session-url: /session/invalid
    permit-all:
    - /event/**
  web:
    ajax-request-key: "X-Requested-With"
    ajax-request-value: "XMLHttpRequest"